### ISSUE TITLE
lat/lng order issue

### ISSUE THREAD

**Issue by agborkowski** [filipkroca/teltonikaparser#1]
https://github.com/filipkroca/teltonikaparser/blob/5647cd38ce53578fb290d834e7a1ebd2d0fa61d0/teltonikaparser.go#L126

hey, first of all super cool library! i see issue  wit lat and lng positions I think should be inverted, cause documentation shows GPS element in order lng then lat... base on (https://wiki.teltonika-gps.com/view/Codec)

**Comment by filipkroca** [comment]
Hi Andrzej, thanks. You are correct, it is not in the correct order. I will do a patch.

**Comment by filipkroca** [comment]
Fixed in [40b1f00](https://github.com/filipkroca/teltonikaparser/commit/40b1f006a6c0870ccd0a49fe639cd313e9a1e091). Thanks for debugging.
