### ISSUE TITLE
Parseable packet structure

### ISSUE THREAD

**Issue by Sakvojage** [filipkroca/teltonikaparser#3]
Hi,
I am looking at Your parser and it does seem to be compatible with Codec8E or I miss something.
https://wiki.teltonika-gps.com/view/Codec#Codec_8_Extended
Could You please break down the structure of the packet in Your example:

stringData=
**0086cafe0101**
_000f333532303933303835363938323_
0368e0100000167efa919800200000000000000000000000000000000fc0013000800ef0000f00000150500c80000450200010000710000fc00000900b5000000b600000042305600cd432a00ce6064001100090012ff22001303d1000f0000000200f1000059d900100000000000000000010086cafe0191000f3335323039333038353639383230368e0100000167efad92080200000000000000000000000000000000fc0013000800ef0000f00000150500c80000450200010000715800fc01000900b5000000b600000042039d00cd432a00ce60640011015f0012fd930013036f000f0000000200f1000059d900100000000000000000010086cafe01a0000f3335323039333038353639383230368e01000000f9cebaeac80200000000000000000000000000000000fc0013000800ef0000f00000150000c80000450200010000710000fc00000900b5000000b600000042305400cd000000ce0000001103570012fe8900130196000f0000000200f10000000000100000000000000000010083cafe0101000f3335323039333038353639383230368e0100000167f1aeec00000a750e8f1d43443100f800b210000000000012000700ef0000f00000150500c800004501000100007142000900b5000600b6000500422fb300cd432a00ce60640011000700120007001303ec000f0000000200f1000059d90010000000000000000001

**Preamble doesnt make sense.. what is it?**
_Why do You attach IMEI part?_
I could not figure out the rest - where and how many times does it include number of data etc. - always getting "Probably not Teltonika, trashed"

Thanks for help.

**Comment by Sakvojage** [comment]
nevermind, its UDP packed. I was trying to shove TCP packet instead.

**Comment by agborkowski** [comment]
check this one ... @spankie shows how to work with TCP https://github.com/spankie/teltonikaparser, TCP keeps connection with server 1. [teltonika] opens connection and sends IMEI 2. [teltonika] sends codec8 packets 3. [server] should sends ack, as u can see UDP is a different a little bit...
